### ISSUE TITLE
trascriptions.create return incomplete Interface Transcription

### ISSUE THREAD

**Issue by leorr** [openai/openai-node#1099] opened 2024-09-26 03:44 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Type of return from openai.audio.transcriptions.create does not seems to have any segments property.
```
const openai = new OpenAI({
    apiKey: ...
});

const transcription = await openai.audio.transcriptions.create({
      file: file,
      model: 'whisper-1',
      response_format: "verbose_json",
      timestamp_granularities: ["word"]
    });

    logger.info(transcription.segments)
```

### To Reproduce

1. Might be needed to use typescript, might be related to typescript type checking
2. Create a new OpeanAI()
3. Use openai.chat.transcriptions.create()
4. Try to use the segments property from the previous step

### OS

Linux

### Node version

Node v20.17.0

### Library version

openai v4.63

**Comment by RobertCraigie** [comment] 2024-09-26 22:41
Thanks for the report, this is a duplicate of #702. We're hoping to ship a fix tomorrow.

**Closed by RobertCraigie** 2024-09-26 22:41 UTC
Labels: bug
