### ISSUE TITLE
TS7030: Not all code paths return a value

### ISSUE THREAD

**Issue by AmitMY** [openai/openai-node#422] opened 2023-11-04 21:25 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

When building using `tsc` with `openai` as a dependency, I get the following error:
node_modules/openai/src/lib/AbstractChatCompletionRunner.ts(224,28): error TS7030: Not all code paths return a value.

I also had to disable the `noImplicitAny` rule since `openai` is not built, and then my app build inherits your source code basically.

### To Reproduce

`const OpenAI = require('openai');`

and build with `tsc` 

(Ideally, I would like this to be an automated test for this library, so build errors do not repeat.)

### OS

macOS, ubuntu

### Node version

Node 18

### Library version

4.15.1

**Comment by rattrayalex** [comment] 2023-11-04 21:28
Thanks for reporting. Can you share your tsconfig?

**Comment by AmitMY** [comment] 2023-11-06 08:15
As mentioned, I am importing `openai` like so: `const OpenAI = require('openai');` in runtime.
I am also importing types in advance - `import type OpenAI from 'openai';`

My `tsconfig.json` is:
```ts
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "moduleResolution": "node",
    "types": ["node", "jest"],
    "resolveJsonModule": true,
    "useUnknownInCatchVariables": false,
    "noImplicitAny": false
  },
  "compileOnSave": true,
  "include": ["src"]
}
```

**Comment by rattrayalex** [comment] 2023-11-07 01:44
Thanks. What version of TypeScript are you using?

**Comment by rattrayalex** [comment] 2023-11-07 01:48
I can't reproduce this error on TypeScript 5.2, 4.9, or 4.5. Could you please provide a stackblitz or similar repo that reproduces the problem?

**Comment by AmitMY** [comment] 2023-11-07 09:51
my code base for exact repro:
```bash
git clone https://github.com/sign/translate.git
cd translate/functions
npm install
tsc
```

<img width="949" alt="image" src="https://github.com/openai/openai-node/assets/5757359/ae4657f1-25b9-4274-99db-9bc3c5b29dd2">

**Comment by gommzystudio** [comment] 2023-11-07 13:59
Hey,
I temporary fixed the issue by adding

```
"noImplicitReturns": false,
"strict": false,
```

to my tsconfig.

**Comment by RobertCraigie** [comment] 2023-11-07 17:29
Thanks for reporting! A fix for this will be included in the next release.

**Closed by RobertCraigie** 2023-11-07 17:29 UTC
Labels: bug

**Comment by AmitMY** [comment] 2023-11-09 13:48
Thanks. With the new release, the only remaining error is:
> node_modules/openai/src/streaming.ts(187,18): error TS7006: Parameter 'ctrl' implicitly has an 'any' type.

**Comment by RobertCraigie** [comment] 2023-11-09 14:01
@AmitMY The issue is that you're importing from `openai/src`, the `src/` path is only included to help IDEs with "go to source" calls etc.

If you change this line:

```ts
import type {ChatCompletionMessageParam} from 'openai/src/resources/chat/completions';
```

to this:

```ts
import type {ChatCompletionMessageParam} from 'openai/resources/chat/completions';
```

Then everything should work.

**Comment by AmitMY** [comment] 2023-11-09 15:18
my bad! thanks :)
