### ISSUE TITLE
Deprecation Warning for `punycode` Module Usage

### ISSUE THREAD

**Issue by nachodeh** [openai/openai-node#750] opened 2024-04-02 09:45 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hello,

I've encountered a deprecation warning in my project that appears to be originating from this library. When running my Next.js application, the following deprecation warning is emitted:

`(node:14106) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.`

When removing the OpenAI dependency, the warning is gone.

### To Reproduce

1. Add the openai dependency: `import OpenAI from "openai"`
2. Run `next build`

### OS

macOS

### Node version

v21.7.1

### Library version

4.32.0

**Comment by rattrayalex** [comment] 2024-04-03 06:13
This is a duplicate of https://github.com/openai/openai-node/issues/527

**Closed by rattrayalex** 2024-04-03 06:13 UTC
Labels: bug
