### ISSUE TITLE
Module not found error on v4.5.0

### ISSUE THREAD

**Issue by gxara** [openai/openai-node#296] opened 2023-09-07 20:43 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

I was following the[ tutorial to integrate nextjs with openai](https://sdk.vercel.ai/docs/getting-started) and noticed that the latest release (v4.5.0) is throwing a module not found error.

```
./node_modules/.pnpm/openai@4.5.0/node_modules/openai/core.mjs:32:0
Module not found: Can't resolve 'openai/_shims/agent.mjs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/openai@4.5.0/node_modules/openai/index.mjs
./pages/api/completion.ts
./node_modules/.pnpm/next@13.4.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=%2Fhome%2Fgxara%2FPessoal%2FProjetos%2Fknowledge-tree%2Fpages%2Fapi%2Fcompletion.ts&page=%2Fapi%2Fcompletion&rootDir=%2Fhome%2Fgxara%2FPessoal%2FProjetos%2Fknowledge-tree&preferredRegion=!
```

Maybe this is something related to this change: 

![image](https://github.com/openai/openai-node/assets/33765053/0976e877-f535-41ad-89aa-39e34ad33e87)

Important: I did a downgrade to version v4.4.0 and everything worked as expected.

### To Reproduce

1. Install release v4.5.0
2.  `import OpenAI from "openai";`

### OS

Debian

### Node version

Node v18.17.1

### Library version

openai v4.5.0

**Comment by lautapercuspain** [comment] 2023-09-07 21:13
I can repro the same, but without using the Vercel AI SDK in this particular project I'm working on.
I can repro exactly the same in a Vercel function.

**Comment by jlia0** [comment] 2023-09-07 22:04
Having the same issue too! I'm beyond confused how this happened.

**Comment by lautapercuspain** [comment] 2023-09-07 23:48
@jlia0 you could downgrade to v4.4.0 and it should work as expected.

**Comment by lautapercuspain** [comment] 2023-09-07 23:51
BTW Folks - I guess **Vercel** does not support using the `openai-node` lib directly because an incompatibility with the Axios lib. _Please correct me if am wrong_

**Comment by aomi** [comment] 2023-09-07 23:58
@lautapercuspain This is a problem in Node.js environments (so the Vercel Serverless offering running on Node). 
I haven't noticed any issues with it running on our Edge Functions.

**Comment by rattrayalex** [comment] 2023-09-08 00:01
Sorry about this! We're working on a fix.

**Comment by rattrayalex** [comment] 2023-09-08 00:46
I could use some help reproducing this – when I follow the [linked tutorial](https://sdk.vercel.ai/docs/getting-started) and run `pnpm run dev` or `pnpm run build && pnpm run start`, it works without complaint. 

Does the error only occur when deploying to Vercel?

**Comment by jedwards1211** [comment] 2023-09-08 03:37
@gxara I'm curious what your webpack config is, I think webpack must be resolving modules in a weird way... could you put something like this in your `next.config.js` and paste what it prints out here?

```js
** @type {import('next').NextConfig} */
const nextConfig = {
  webpack(config, opts) {
    console.log(config, opts);
    return config;
  },
  // ...
};

module.exports = nextConfig;
```
And can you share your `package.json`?

**Comment by aomi** [comment] 2023-09-08 04:14
I've made a similar repro project as above https://github.com/aomi/repro-296 with the same findings.
Works fine locally (`npm run dev` and also with it built using `npm build` ran with `npm start`).  Node v20.5.1 locally. 
The endpoint that uses the page dir ends up erroring out. 

Stock configuration with the `next.config.js` with the only package added being `openai`.

**Comment by zwben** [comment] 2023-09-08 15:53
I met this problem after migrating from v3 to v4 following the instruction [](https://github.com/openai/openai-node/discussions/217) . I also tried v4.0.0, v4.4.0, and v4.5.0, but all of them raised the error. Then I check the source code and found that the import statment is from openai folder: `import { fetch, isPolyfilled as fetchIsPolyfilled } from 'openai/_shims/fetch.mjs';` in the core.mjs for example, but core.mjs and _shims folder are already in the openai folder. So I wonder if I missed any dependencies which can address this relative path or work directory issue.

**Comment by rattrayalex** [comment] 2023-09-08 18:50
Thank you @aomi ! The `encoding` printout is just a warning that is safe to ignore.

**Comment by rattrayalex** [comment] 2023-09-08 18:51
@zwben I suspect you're encountering a slightly different issue; can you paste the traceback? It'd be very helpful if you could share a repo with full repro as well if you can.

**Comment by zwben** [comment] 2023-09-08 20:12
> @zwben I suspect you're encountering a slightly different issue; can you paste the traceback? It'd be very helpful if you could share a repo with full repro as well if you can.

Here is the repo. https://github.com/zwben/ouhcir-frontend/tree/fa06087bf4528348426f3f860e3ccce940429fa0
I changed openai version from 3.3.0 to 4.0.0 in the package.json, rerun `npm install`, and used grit to migrate the update. Then `npm start` raised errors:
```
Module not found: Error: Can't resolve 'openai/_shims/agent.mjs' in 'H:\Dataspeedup\ouhcir-frontend-copy\node_modules\openai'
ERROR in ./node_modules/openai/core.mjs 16:0-58
Module not found: Error: Can't resolve 'openai/_shims/agent.mjs' in 'H:\Dataspeedup\ouhcir-frontend-copy\node_modules\openai'

ERROR in ./node_modules/openai/core.mjs 17:0-83
Module not found: Error: Can't resolve 'openai/_shims/fetch.mjs' in 'H:\Dataspeedup\ouhcir-frontend-copy\node_modules\openai'

more similar errors...
```

**Comment by jedwards1211** [comment] 2023-09-08 22:43
Okay we have a fix for OP coming in the next release!

@zwben I think you are having a separate issue though, I will investigate

**Comment by jedwards1211** [comment] 2023-09-08 22:52
@zwben okay the next release will fix the errors on your project as well.

Note: you're actually on version 4.5.0; in your `package.json` you have [`"openai": "^4.0.0"`](https://github.com/zwben/ouhcir-frontend/blob/fa06087bf4528348426f3f860e3ccce940429fa0/package.json#L11), [the `^`](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004) means use any 4.x.x version >= 4.0.0, and indeed it [resolved to `4.5.0` in your `package-lock.json`](https://github.com/zwben/ouhcir-frontend/blob/fa06087bf4528348426f3f860e3ccce940429fa0/package-lock.json#L19164), so you are actually on 4.5.0 and seeing the same issue as others here.

**Comment by rattrayalex** [comment] 2023-09-08 23:23
Released in 4.6.0

**Closed** 2023-09-08 23:23 UTC
Labels: bug

**Comment by lautapercuspain** [comment] 2023-09-09 01:21
Awesome, thanks @rattrayalex !

**Comment by zwben** [comment] 2023-09-09 14:19
Thanks, the new release addressed my problem @rattrayalex

**Comment by JackLazenbyZigzag** [comment] 2023-09-09 23:36
Hi there, I'm still having this issue on the latest version (4.6.0) ; however, this happens when I try to run tests in Jest, rather than when deploying an app. 

It builds and runs fine locally as an app, I can get responses etc no problem, but it has broken my test suite so I can't deploy it into production just yet. 

It's a NestJS (not nextjs) API this is happening in. Below is the error we get:

ReferenceError: fetch is not defined

      1 | import {Injectable} from "@nestjs/common";
      2 | import {ChatCompletionMessageParam} from "openai/resources/chat";
    > 3 | import OpenAI from 'openai';

at Object.<anonymous> (../../../../node_modules/openai/_shims/fetch.js:8:17)
at Object.<anonymous> (../../../../node_modules/openai/core.js:64:17)
at Object.<anonymous> (../../../../node_modules/openai/src/index.ts:116:7)


Thanks!
