### ISSUE TITLE
Vision API with Azure OpenAI doesn't return any usage details like tokens used

### ISSUE THREAD

**Issue by Ahmet-Dedeler** [openai/openai-node#673] opened 2024-02-14 20:22 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Not sure if this is only occurs with Azure OpenAI, but the response doesn't contain usage credits at all.

Example response:
```json
{
  "choices": [
    {
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      },
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "The response here",
        "role": "assistant"
      }
    }
  ],
  "created": 0,
  "id": "",
  "model": "",
  "object": "chat.completion",
  "prompt_filter_results": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ]
}
```

### To Reproduce

Use Vision API with Azure OpenAI Endpoint.

### OS

Windows 11

### Node version

Node v20.11.0

### Library version

openai v4.28.0

**Comment by rattrayalex** [comment] 2024-02-15 05:41
cc @kristapratico

**Comment by rattrayalex** [comment] 2024-02-15 05:42
Thanks for reporting!  

This sounds like an issue with the underlying API and not the Node library, so I'm going to go ahead and close this issue.

**Closed by rattrayalex** 2024-02-15 05:42 UTC
Labels: bug

**Comment by kristapratico** [comment] 2024-02-15 18:57
@Ahmet-Dedeler I'm not able to reproduce this; I see usage details as long as I'm not streaming the response. Could you share more details about the model and API version you're using, and add an example of how you're calling the vision API?
