### ISSUE TITLE
JSONSchema does not support recursive refs & zod also fails to convert similar schemas to JSONSchema correctly

### ISSUE THREAD

**Issue by mattgi** [openai/openai-node#970] opened 2024-08-07 11:34 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Copy and pasting example schemas (zod included) from the latest documents results in errors when using the latest openai sdk and having a focus on $ref for the new response_format that supports JSONSchema.

zods example @ https://platform.openai.com/docs/guides/structured-outputs/ui-generation
```
 Invalid schema for response_format 'ui': In context=('properties', 'children', 'items'), reference to component '#' which was not found in the schema.
```

and any JSONSchema example I've tried (e.g. https://platform.openai.com/docs/guides/structured-outputs/recursive-schemas-are-supported)

```
2 | import { castToError } from "./core.mjs";
3 | export class OpenAIError extends Error {
4 | }
5 | export class APIError extends OpenAIError {
6 |     constructor(status, error, message, headers) {
7 |         super(`${APIError.makeMessage(status, error, message)}`);
                          ^
error: 500 The server had an error while processing your request. Sorry about that!
      at new OpenAIError (:1:23)
      at new APIError (/node_modules/openai/error.mjs:7:9)
      at new InternalServerError (:1:23)
      at generate (/node_modules/openai/error.mjs:62:20)
      at /node_modules/openai/core.mjs:312:30
```

Initial debugging suggests that the Zod to JSONSchema conversion code looks for `definitions` and `$defs` is not considered.. but then when the resulting schema is used, it requires `$defs` 🤷 so the generated schema from zod is invalid). For the JSONSchema, it struggles with a lot but when I get it to pass the simple syntax validation, it falls over on the server and I cannot figure out where the issue lies based on the error.

### To Reproduce

1. Install latest "openai": "^4.55.0"
2. copy any of the zod or schemas that include definitions, $defs, or recursive schemas.
3. invoke the API via any of the usual ways with the new `response_format`
```ts
const stream = openai.beta.chat.completions
  .stream({
    model: "gpt-4o-2024-08-06",
    max_tokens: 16384,
    response_format: { type: "json_schema", json_schema: schema },
    ...
```

(helps to also include `DEBUG=true` when running though nothing valuable appears to be thrown)

### OS

macOS

### Node version

bun 1.1.20

### Library version

4.55.0

**Comment by RobertCraigie** [comment] 2024-08-07 12:10
Thanks for the report, I can reproduce the error you're seeing. We're investigating.

**Comment by RobertCraigie** [comment] 2024-08-07 14:52
This will be fixed in the next release :) https://github.com/openai/openai-node/pull/969

**Comment by RobertCraigie** [comment] 2024-08-07 15:00
@mattgi please try again with `v4.55.1`!

**Closed by RobertCraigie** 2024-08-07 15:00 UTC
Labels: bug

**Comment by mattgi** [comment] 2024-08-08 00:12
Thanks @RobertCraigie . We are further along, but still not conforming to schema specs afaict.

The Zod schema I am trying:
```ts
const Node = z.lazy(() =>
  z
    .object({
      name: z.string(),
    })
    .and(
      z.union([
        z.object({
          value: z.string().describe("The text content of the node"),
        }),
        z.object({
          css: z.string().describe("A string of all CSS classes to be applied to the element"),
          props: z
            .array(
              z.object({
                key: z.string(),
                value: z.string(),
              }),
            )
            .describe("Attributes of an element"),
          children: z.array(Node),
        }),
      ]),
    ),
);
```

```
400 Invalid schema for response_format 'view': In context=('properties', 'node'), 'allOf' is not permitted
```

There are comments in the openai doco about using `anyOf` instead of `allOf` if you run into this limitation. However, when you use Zod it attempt to use `allOf`.

I would prefer to stick with JSONSchema in any case and it passes to the server without error now. The server however still throws: ` 500 The server had an error while processing your request. Sorry about that!`

The example:
```json
{
  "name": "view",
  "description": "A schema to describe the contents of a view",
  "strict": true,
  "schema": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the view"
      },
      "node": {
        "$ref": "#/$defs/Node"
      }
    },
    "required": ["name", "node"],
    "additionalProperties": false,
    "$defs": {
      "Node": {
        "anyOf": [
          {
            "$ref": "#/$defs/TextNode"
          },
          {
            "$ref": "#/$defs/ElementNode"
          }
        ]
      },
      "TextNode": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "value": {
            "type": "string",
            "description": "The text content of the node"
          }
        },
        "description": "A text node",
        "required": ["name", "value"],
        "additionalProperties": false
      },
      "ElementNode": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the element"
          },
          "css": {
            "type": "string",
            "description": "A string of all CSS classes to be applied to the element"
          },
          "props": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": { "type": "string" },
                "value": { "type": "string" }
              },
              "required": ["key", "value"],
              "description": "Attribute of an element",
              "additionalProperties": false
            },
            "description": "Attributes of an element",
            "additionalProperties": false
          },
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/$defs/Node"
            }
          }
        },
        "description": "An element node that can house any HTML element",
        "required": ["name", "css", "props", "children"],
        "additionalProperties": false
      }
    }
  }
}
```

**Comment by mattgi** [comment] 2024-08-08 10:19
Ok, so a very simplified version works:
```ts
interface Node {
  name: string;
  value?: string;
  css?: string;
  props?: Array<{
    key: string;
    value: string;
  }>;
  children?: Node[];
}

const NodeSchema: z.ZodType<Node> = z.lazy(() =>
  z
    .object({
      name: z.string().describe("The name of the element"),
      value: z.string().optional().describe("The text content of the node"),
      css: z.string().optional().describe("A string of all CSS classes to be applied to the element"),
      props: z
        .array(
          z
            .object({
              key: z.string(),
              value: z.string(),
            })
            .strict()
            .describe("Attribute of an element"),
        )
        .optional()
        .describe("Attributes of an element"),
      children: z.array(NodeSchema).optional(),
    })
    .describe("An element node that can house any HTML element"),
);
```
This aligns with the example included in ur PR @RobertCraigie but it's still not the recursive + anyOf idea I was hoping for.
Trying to use the JSONSchema with anyOf seems to always result in a server error too 🤷.

**Comment by RobertCraigie** [comment] 2024-08-08 10:51
ah @mattgi, the reason it tries to use an `allOf` is because of the `.and()` in your original example.

I haven't verified it yet but you should be able to retain your `.union()` by adding `name: z.string()` to each variant.

I'll see if we can improve the experience here regardless.

**Comment by mattgi** [comment] 2024-08-08 10:56
I've tried so many variations I can't remember what I have and haven't tried 🤣. I think the tldr; is that I think i have something that works well enough for my use case, but I would anticipate a lot of issues being reported once people start to try to use complex schemas. The debugging experience is difficult to crack.

I also never got my JSONSchema version to work - validation for it was at least passing, but it was then the server falling over.

**Comment by RobertCraigie** [comment] 2024-08-08 10:57
> I also never got my JSONSchema version to work - validation for it was at least passing, but it was then the server falling over.

Do you have a request ID for any of your failing requests?

**Comment by mattgi** [comment] 2024-08-08 11:16
its doing work, thats for sure.. takes a very long time before the server throws.

I just get this.. 
```
2 | import { castToError } from "./core.mjs";
3 | export class OpenAIError extends Error {
4 | }
5 | export class APIError extends OpenAIError {
6 |     constructor(status, error, message, headers) {
7 |         super(`${APIError.makeMessage(status, error, message)}`);
                          ^
error: 500 The server had an error while processing your request. Sorry about that!
      at new OpenAIError (:1:23)
      at new APIError (/node_modules/openai/error.mjs:7:9)
      at new InternalServerError (:1:23)
      at generate (/node_modules/openai/error.mjs:62:20)
      at /node_modules/openai/core.mjs:311:30
```

**Comment by mattgi** [comment] 2024-08-08 11:19
(just realised I can turn debug on.. )...  `"x-request-id": "req_b42e7318670076bf595c56af2e28801b",`
