### ISSUE TITLE
functions calling returning an undocumented `multi_tool_use.parallel` case 

### ISSUE THREAD

**Issue by alxpereira** [openai/openai-node#488] opened 2023-11-12 13:05 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hello, 
I'm encountering an undocumented use of the function calling feature, using the new assistant/threads features via the SDK.
In some occasions (happened already 3x today), the function calling is returning a structure as in the screenshot below. 

Please note that this behavior is random. Not happening 100% of the time, so maybe related to an underlying issue, but no-one from openai has replied to the initial thread. 

![image](https://github.com/openai/openai-node/assets/447895/de933bf8-2b27-4c20-819d-7cd55bc9cb58)

Any knowledge of this ?
Thanks

Original thread in the community:
https://community.openai.com/t/model-tries-to-call-unknown-function-multi-tool-use-parallel/490653/6

### To Reproduce

Seems like related to complex calls, the model looking like it wants to parallelize function call executions.

### OS

macOS

### Node version

Node v21.1.0

### Library version

openai v4.12.4

**Comment by BjoernRave** [comment] 2023-11-12 21:36
I dont really get why both exists, but you tried with `runTools` ?

**Comment by rattrayalex** [comment] 2023-11-14 03:30
Thanks for reporting, I'll pass it along.

I'm going to go ahead and close this issue because it's not a bug in the TypeScript library.

**Closed by rattrayalex** 2023-11-14 03:30 UTC
Labels: bug
