### ISSUE TITLE
Chat completion stream returns empty total usage

### ISSUE THREAD

**Issue by JosePina98** [openai/openai-node#506] opened 2023-11-16 10:58 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Using openai.beta.chat.completions.stream() and then calling totalUsage function returns the object with all values set to zero.

### To Reproduce

1. Call the chat completions API with response stream
2. Log the result of totalUsage function
3. Check that every value is zero

### Code snippets

```JavaScript
const response = openai.beta.chat.completions.stream({
    messages: [
        {
            role: "user",
            content: "hello"
        }
    ],
    model: "gpt-3.5-turbo-1106",
    response_format: { type: "text" },
    max_tokens: 300,
    n: 1,
    temperature: 1.2,
    stream: true
});

console.log(await response.totalUsage())
```

### OS

Ubuntu

### Node version

Node v16.13.0

### Library version

open v4.19.0

**Comment by clickeo-dev** [comment] 2023-11-17 10:40
I can confirm that this issue still exist. @JosePina98 did you find any workaround on this?

**Comment by JosePina98** [comment] 2023-11-17 10:45
For now I have created this Typescript function to estimate the tokens used in each call. According to the tests I've done, it makes a rough estimate, but on the high end.

`
const tokenEstimation = (prompt: string, output: string): {
    prompt_tokens: number,
    completion_tokens: number,
    total_tokens: number
} => {

    const tokenLength = 3.8;

    const promptTokens = Math.ceil(prompt.length / tokenLength);
    const completionTokens = Math.ceil(output.length / tokenLength);
    return {
        prompt_tokens: promptTokens,
        completion_tokens: completionTokens,
        total_tokens: promptTokens + completionTokens
    }
}
`

**Comment by clickeo-dev** [comment] 2023-11-17 10:52
> For now I have created this Typescript function to estimate the tokens used in each call. According to the tests I've done, it makes a rough estimate, but on the high end.
> 
> ```js
> const tokenEstimation = (prompt: string, output: string): {
>     prompt_tokens: number,
>     completion_tokens: number,
>     total_tokens: number
> } => {
> 
>     const tokenLength = 3.8;
> 
>     const promptTokens = Math.ceil(prompt.length / tokenLength);
>     const completionTokens = Math.ceil(output.length / tokenLength);
>     return {
>         prompt_tokens: promptTokens,
>         completion_tokens: completionTokens,
>         total_tokens: promptTokens + completionTokens
>     }
> }
> ```

I do kinda same. Using the [tokenizer](https://github.com/niieani/gpt-tokenizer) package since the package doesn't support new models I hard coded 'gpt-4' as model. I assume that they are all using `cl100k_base` encoding model under the hood.

```js
 // Calculate Token Sizes
        const inputTokenSize = tokenizer.encodeChat(
          messages,
          "gpt-4"
        ).length;
        const outputTokenSize = tokenizer.encodeChat(
          [
            {
              role: "assistant",
              content: output,
            },
          ],
          "gpt-4"
        ).length;
```

**Comment by rattrayalex** [comment] 2023-11-18 23:06
Sorry about this, `usage` events are not sent in streaming just yet; we hope to add that to the API soon.

It was arguably a mistake to include `totalUsage()` on that interface before it was ready in the API, sorry for the confusion.

**Comment by yauri-io** [comment] 2023-12-06 08:35
Hitting this issue as well. I see this issue's status is Closed, but I couldn't see any new release with the fix.
Any ETA?

**Comment by rattrayalex** [comment] 2023-12-15 03:19
cc @athyuttamre

**Comment by athyuttamre** [comment] 2023-12-15 05:13
Hi folks, we pre-emptively added the `totalUsage()` function but unfortunately have not released support in the API just yet. We plan to do so early next year. Sorry for the confusion, but feel free to subscribe to this GitHub issue and we'll post here when it is launched.

**Comment by talos** [comment] 2023-12-19 03:48
Glad to hear it! Would it be possible to re-open the ticket to make it clearer when this has been resolved?

**Comment by jay-pulsifi** [comment] 2024-02-15 01:36
Hi team, any ETA when this ticket will be resolved?

**Comment by aar2dee2** [comment] 2024-02-29 12:01
following this for updates

P.S. thanks for the `stream` events - have made it easy to work with db calls when streaming completions!

**Comment by Mickeygogo** [comment] 2024-03-17 15:29
When are you going to put this issue on to resolution?

**Comment by nai-kon** [comment] 2024-03-21 07:46
I am really looking forward to usage support on stream mode.

**Comment by donprasetiyo** [comment] 2024-06-11 11:38
The Python one has been shipped. Is there an estimate for the node?

**Comment by decline** [comment] 2024-06-26 12:23
I'm using version `4.51.0` and I just found out there is a `stream_options` property that can contain `include_usage: true`, example:

```ts
 const stream = this.openAi.beta.chat.completions.stream({
      model: 'gpt-3.5-turbo',
      messages: [{ role: 'user', content: 'Say something funny' }],
      stream: true,
      max_tokens: 5,
      stream_options: {
        include_usage: true
      }
    });
```

When using it like this, you are able to either use the `stream.totalUsage()` promise or the `stream.on('totalUsage', usage => {})` callback. In both cases, you will receive:

```ts
{ completion_tokens: 5, prompt_tokens: 10, total_tokens: 15 }
```

Not sure if this feature was added silently, or nobody noticed?

**Comment by nai-kon** [comment] 2024-07-22 05:52
It seems usage option on streaming was supported on May 6th. 
Here is a release note.

https://platform.openai.com/docs/changelog/may-6th-2024
![image](https://github.com/user-attachments/assets/f383648c-4b1c-4740-9d1f-13e8c0977462)

Can we close this issue?

**Comment by Mickeygogo** [comment] 2024-07-22 06:03
yes

要买直升机的Mickey
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openai/openai-node"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openai/openai-node] Chat completion stream returns empty total usage (Issue #506)





 
It seems the usage option on streaming was supported on May 6th.
 Here is a release note.
 
https://platform.openai.com/docs/changelog/may-6th-2024
 image.png (view on web)
 
Can we close this issue?

**Comment by rattrayalex** [comment] 2024-07-22 15:49
As @decline [noted](https://github.com/openai/openai-node/issues/506#issuecomment-2191557109), you can now access total usage data by passing `stream_options: { include_usage: true }`.

**Closed by rattrayalex** 2024-07-22 15:49 UTC
Labels: openai api
