### ISSUE TITLE
4.40.0 -> 4.40.1: Breaking change - OpenAI is not a constructor

### ISSUE THREAD

**Issue by YasharF** [openai/openai-node#816] opened 2024-05-02 18:09 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [x] This is an issue with the Node library

### Describe the bug

Based on numbers, 4.40.1 is supposed to be a bug fix release over 4.40.0, so I didn't expect something to break.  I have not tested the application after 4.40.1 to see if anything else is broken.

const openai = new OpenAI({
               ^

TypeError: OpenAI is not a constructor

### To Reproduce

Code saved as test.js:
```
const openaiKey = "a valid OpenAI key"
const OpenAI = require('openai');

const openai = new OpenAI({
	apiKey: openaiKey,
});

```

```
 >> npm install openai@4.40.0
 >> node test.js
(no errors.)
 >> npm install openai@4.40.1
 >> node test.js
 const openai = new OpenAI({
               ^

TypeError: OpenAI is not a constructor
 >> npm install openai@4.40.0
 >> node test.js
(no errors.)
```

### OS

WSL Ubuntu 24.04 LTS

### Node version

v20.12.2

### Library version

4.40.1

**Comment by bizob2828** [comment] 2024-05-02 19:14
At New Relic we instrument this package and this behavior is causing issues.  I want to echo from what @YasharF has said that this was released in a patch and is a breaking change

**Comment by Galkon** [comment] 2024-05-02 22:39
Using this package in a project and 4.40.1 breaks production builds due to this error. Works in local development environment. Reverting to 4.40.0 fixes it.

**Comment by mtharrison** [comment] 2024-05-03 08:10
Having a similar issue in tests where I stub `OpenAI.Embeddings.prototype` which has now moved to `OpenAI.OpenAI.Embeddings.prototype`

**Comment by Eomm** [comment] 2024-05-03 08:41
This bot PR seems the root cause 😄 
https://github.com/openai/openai-node/pull/815

**Comment by RobertCraigie** [comment] 2024-05-03 12:08
sorry about this, we're investigating.

**Comment by RobertCraigie** [comment] 2024-05-03 12:09
does anyone have a minimal reproduction?

**Comment by rattrayalex** [comment] 2024-05-03 12:22
Thanks for reporting. Can you share your tsconfig to aid with repro?

**Comment by mahaboobkhan29** [comment] 2024-05-03 12:24
Ahh... i thought my code have some issue...    

const  OpenAI  = require("openai");
const openai = new OpenAI({
    apikey: process.env.OPENAI_API_KEY
});

**OpenAI is not a constructor**


Are you guys investigating this???

**Comment by jsumners-nr** [comment] 2024-05-03 12:33
> Thanks for reporting. Can you share your tsconfig to aid with repro?

The reproduction supplied in the opening report is plain JavaScript plus Node.js. There is no TypeScript involved.

**Comment by mtharrison** [comment] 2024-05-03 13:18
>Thanks for reporting. Can you share your tsconfig to aid with repro?

My report is also from a is in a pure JS repo. As reported above it works ok using ESM but CJS is where it fails.

**Comment by mtharrison** [comment] 2024-05-03 13:43
Minimal repo is simply:
```js
const OpenAi = require('openai');
const client = new OpenAi();
```
```sh
$ node index.js
TypeError: OpenAi is not a constructor.....
```

**Comment by RobertCraigie** [comment] 2024-05-03 13:44
this will be fixed in the next release: https://github.com/openai/openai-node/pull/818

**Comment by mahaboobkhan29** [comment] 2024-05-03 13:47
@RobertCraigie  when can we expect the fix version release in NPM

**Comment by RobertCraigie** [comment] 2024-05-03 14:30
This has been fixed in `v4.40.2`

**Closed by RobertCraigie** 2024-05-03 14:30 UTC
Labels: bug

**Comment by canws** [comment] 2024-05-03 17:03
Thanks a lot , finally working this.

**Comment by dreamsavior** [comment] 2024-06-16 00:15
> This has been fixed in `v4.40.2`

No, this hasn’t been fixed. I’m still having the problem on the latest version, 4.51.

**Comment by ygorcarmo** [comment] 2024-06-18 05:32
Same here but only after I tried to implement datadog.

**Comment by dgellow** [comment] 2024-06-18 14:06
@dreamsavior Please open another GitHub issue if you're still having problems with the latest version of the SDK
