### ISSUE TITLE
throw Error when set baseUrl undefined.

### ISSUE THREAD

**Issue by arvinxx** [openai/openai-node#283] opened 2023-09-04 15:11 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

create OpenAI with baseURL = undefined ,will case error:

 [TypeError: Cannot read properties of undefined (reading 'endsWith')]

### To Reproduce

create 
```
  const baseURL = OPENAI_PROXY_URL ? OPENAI_PROXY_URL : undefined;

  return new OpenAI({
    apiKey: !userApiKey ? OPENAI_API_KEY : userApiKey,
    baseURL: OPENAI_PROXY_URL ? OPENAI_PROXY_URL : undefined;
  });
```

### Code snippets

the problem is this line: https://github.com/openai/openai-node/blob/master/src/core.ts#L404

### OS

macOS 13

### Node version

18

### Library version

4.4.0

**Comment by rattrayalex** [comment] 2023-09-04 15:24
What is your intended behavior in passing `baseURL: undefined`?

**Comment by arvinxx** [comment] 2023-09-04 15:35
> What is your intended behavior in passing baseURL: undefined?


use the `openai` default endpoint

**Comment by arvinxx** [comment] 2023-09-04 15:38
here is my migration from `openai-edge` to `openai`

https://github.com/lobehub/lobe-chat/pull/145/files

the undefined mean that user don't customize the openai proxy, just send request to `https://api.openai.com/v1`.

It works well with `openai-edge`

**Comment by rattrayalex** [comment] 2023-09-04 15:52
Thank you, that makes sense. I agree this is a bug, we will try to have a fix out soon. 

In the meantime, as you're likely aware, you can do this as a workaround:

```ts
const opts =  {
  apiKey: !userApiKey ? OPENAI_API_KEY : userApiKey,
}
if (OPENAI_PROXY_URL) {
  opts.baseURL = OPENAI_PROXY_URL;
}
return new OpenAI(opts);
```

**Comment by rattrayalex** [comment] 2023-09-07 19:55
This was fixed in https://github.com/openai/openai-node/releases/tag/v4.5.0

**Closed by rattrayalex** 2023-09-07 19:55 UTC
Labels: bug
