### ISSUE TITLE
TypeScript compilation errors in backend environment

### ISSUE THREAD

**Issue by jessicazu** [openai/openai-node#363] opened 2023-10-10 15:27 UTC
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hello,

I recently encountered several TypeScript compilation errors when using this library in a backend project.
The issue primarily seems related to missing DOM types.

Here are the errors I encountered when I run `tsc` command:

```
../../node_modules/openai/src/core.ts:39:15 - error TS2304: Cannot find name 'AbortController'.

39   controller: AbortController;
                 ~~~~~~~~~~~~~~~

../../node_modules/openai/src/core.ts:252:18 - error TS2304: Cannot find name 'TextEncoder'.

252       if (typeof TextEncoder !== 'undefined') {
                     ~~~~~~~~~~~

../../node_modules/openai/src/core.ts:253:29 - error TS2304: Cannot find name 'TextEncoder'.

253         const encoder = new TextEncoder();
                                ~~~~~~~~~~~

../../node_modules/openai/src/core.ts:377:28 - error TS2304: Cannot find name 'AbortController'.

377     const controller = new AbortController();
                               ~~~~~~~~~~~~~~~

../../node_modules/openai/src/core.ts:424:13 - error TS2304: Cannot find name 'URL'.

424         new URL(path)
                ~~~

../../node_modules/openai/src/core.ts:425:13 - error TS2304: Cannot find name 'URL'.

425       : new URL(this.baseURL + (this.baseURL.endsWith('/') && path.startsWith('/') ? path.slice(1) : path));
                ~~~

../../node_modules/openai/src/core.ts:460:17 - error TS2304: Cannot find name 'AbortController'.

460     controller: AbortController,
                    ~~~~~~~~~~~~~~~

../../node_modules/openai/src/core.ts:580:31 - error TS2304: Cannot find name 'URL'.

580 export type PageInfo = { url: URL } | { params: Record<string, unknown> | null };
                                  ~~~

../../node_modules/openai/src/core.ts:727:12 - error TS2304: Cannot find name 'AbortSignal'.

727   signal?: AbortSignal | undefined | null;
               ~~~~~~~~~~~

../../node_modules/openai/src/core.ts:1083:14 - error TS2304: Cannot find name 'btoa'.

1083   if (typeof btoa !== 'undefined') {
                  ~~~~

../../node_modules/openai/src/core.ts:1084:12 - error TS2304: Cannot find name 'btoa'.

1084     return btoa(str);
                ~~~~

../../node_modules/openai/src/streaming.ts:13:15 - error TS2304: Cannot find name 'AbortController'.

13   controller: AbortController;
                 ~~~~~~~~~~~~~~~

../../node_modules/openai/src/streaming.ts:18:47 - error TS2304: Cannot find name 'AbortController'.

18   constructor(response: Response, controller: AbortController) {
                                                 ~~~~~~~~~~~~~~~

../../node_modules/openai/src/streaming.ts:208:16 - error TS2304: Cannot find name 'TextDecoder'.

208     if (typeof TextDecoder !== 'undefined') {
                   ~~~~~~~~~~~

../../node_modules/openai/src/streaming.ts:210:34 - error TS2304: Cannot find name 'TextDecoder'.

210         this.textDecoder ??= new TextDecoder('utf8');
                                     ~~~~~~~~~~~

../../node_modules/openai/src/uploads.ts:112:18 - error TS2304: Cannot find name 'URL'.

112     name ||= new URL(value.url).pathname.split(/[\\/]/).pop() ?? 'unknown_file';
                     ~~~


Found 16 errors in 3 files.

Errors  Files
    11  ../../node_modules/openai/src/core.ts:39
     4  ../../node_modules/openai/src/streaming.ts:13
     1  ../../node_modules/openai/src/uploads.ts:112
```

For reference, my tsconfig.json is as follows:
```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "outDir": "./dist", 
    "lib": ["es2020"],
    "typeRoots": ["./node_modules/@types", "./types"],
    "baseUrl": ".",
    "resolveJsonModule": true
  },
  "exclude": ["cdk.out", "node_modules"]
}
```

While adding the `dom` library to `lib` of my tsconfig.json does seem to resolve these errors, it causes references in other parts of the code to inadvertently change, leading to build failures. Furthermore, I believe that adding the dom library to a backend codebase isn't appropriate.

I've verified that the problem is not related to React's StrictMode. Upon checking the openai library's tsconfig.json, I noticed it uses the skipLibCheck option, but adding that to my project's configuration did not resolve the issue.

I wanted to raise this issue here to check if it's a known issue, or if there are any recommended workarounds. Any assistance or guidance would be appreciated.

Thank you.

### To Reproduce

1. yarn add openai
2. run `tsc` on my repository
3. See error

### OS

macOS

### Node version

Node v18.4.0

### Library version

openai v4.8.0

**Comment by rattrayalex** [comment] 2023-10-10 16:53
Is your code importing like `import OpenAI from 'openai'` or like `import OpenAI from 'openai/src'`? Or not at all? The `src` directory within our package isn't intended to be imported or typechecked, it's only there for reference.

I haven't checked this, but you might need `"exclude": ["cdk.out", "node_modules", "../../node_modules"]` – it's surprising that you're excluding node_modules from being checked and still getting errors there.

**Comment by JacobT14** [comment] 2023-10-10 17:24
@rattrayalex I just tried your suggestion and am getting the same error unforunately.

**Comment by rattrayalex** [comment] 2023-10-10 17:29
Hm. This sounds like a problem with your TS setup. Can you share your base tsconfig as well? You may need to restart your TS LSP as well to see the fixes come through.

Can you confirm whether and how you are importing `openai`?

**Comment by rattrayalex** [comment] 2023-10-10 17:39
Hmm, `const { OpenAIApi } = require('openai');` is not correct, try `const { OpenAI } = require('openai');`?

Can you try `"moduleResolution": "NodeNext"`?

**Comment by JacobT14** [comment] 2023-10-10 17:41
Yeah my bad, main point is requiring works (since it's not going through the type files).

No, moduleResolution didn't work

**Comment by rattrayalex** [comment] 2023-10-10 20:47
Hmm, it's quite surprising to me that `require` would work where `import` would not… 

Could you share a StackBlitz repo that reproduces the error?

**Comment by jessicazu** [comment] 2023-10-11 02:34
@rattrayalex 

Thank you for the confirmation.

My `tsconfig.base.json` is as follows:

```
{
  "compilerOptions": {
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "noErrorTruncation": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitAny": false
  },
  "exclude": ["node_modules"]
}
```

By the way, I'm using a monorepo setup. Because I've listed `openai` in the dependencies of the root's `package.json`, `openai` is placed in the root's `node_modules`.

As you suggested, I added `../../node_modules` to the exclude of `/packages/backend/tsconfig.json`, but I still get the same error.
```
"exclude": ["cdk.out", "node_modules", "../../node_modules"]
```

Also, even when I added `"skipLibCheck": true` to /packages/backend/tsconfig.json, the result is the same.

**Comment by jessicazu** [comment] 2023-10-11 02:43
>Is your code importing like import OpenAI from 'openai' or like import OpenAI from 'openai/src'? Or not at all? The src directory within our package isn't intended to be imported or typechecked, it's only there for reference in sourcemaps.

I'm importing in the code like this: `import { OpenAI } from 'openai';`.
However, in certain parts, I want to use a specific type, so I'm importing it as `import { ChatCompletionMessageParam } from 'openai/src/resources/chat/completions';.`

However, even after removing all of these references and running `tsc`, I still encountered the same error.

**Comment by rattrayalex** [comment] 2023-10-11 21:51
Ah. Hmm. You don't want to import `from 'openai/src…'`, it's good you removed `src/` from that.

Could you have the `openai` dependency live in `packages/backend` instead of the root, if you're using it in that package?

**Comment by rattrayalex** [comment] 2023-10-20 20:25
I'm going to close this because I suspect it's due to an idiosyncratic package setup, but please feel free to upvote or comment if it continues to be an issue.

**Closed by rattrayalex** 2023-10-20 20:25 UTC
Labels: bug
